<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/timeline">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/sair">
	  		Sair
	  	</a>
			<img src="/img/twitter_logo.png" class="menuIco" />
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>

				<div class="perfilPainel">
					
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome"><?= $this->view->info_usuario['nome'] ?></span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->total_tweets['total_tweet'] ?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->total_seguindo['total_seguindo'] ?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->total_seguidores['total_seguidores'] ?></span>
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			
			<div class="row mb-2">
				<div class="col">
					<div class="card">
						<div class="card-body">
							<form action="/quem_seguir" method="post">
								<div class="input-group mb-3">
									<input name="search" type="text" value="<?= $this->view->search ?>" class="form-control" placeholder="Quem você está procurando?">
									<div class="input-group-append">
										<button class="btn btn-primary" type="submit">Procurar</button>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>

			<?php foreach($this->view->usuarios as $usuario) { ?>

				<div class="row mb-2">
					<div class="col">
						<div class="card">
							<div class="card-body">
								<div class="row">
									<div class="col-md-6">
										<?= $usuario['nome'] ?>
									</div>
								
									<div class="col-md-6 d-flex justify-content-end">
										<div>

											<?php if($usuario['segue'] == 0) { ?>

												<a href="/action?action=seguir&id_usuario=<?= $usuario['id'] ?>&search=<?= $this->view->search ?>&page=<?= $this->view->current_page ?>" class="btn btn-success">Seguir</a>
												
											<?php } else { ?>
													
												<a href="/action?action=deixar_de_seguir&id_usuario=<?= $usuario['id'] ?>&search=<?= $this->view->search ?>&page=<?= $this->view->current_page ?>" class="btn btn-danger">Deixar de seguir</a>
											
											<?php }; ?>

										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>

			<?php }; ?>

			<div class="row justify-content-center">
				<nav aria-label="...">
					<ul class="pagination">
						<li class="page-item">
							<a class="page-link" href="?page=1&search=<?= $this->view->search ?>">Primeira</a>
						</li>

						<?php for($i = 1; $i <= $this->view->total_paginas; $i++) { ?>

							<li class="page-item <?= $this->view->current_page == $i ? 'active' : '' ?>">
								<a class="page-link" href="?page=<?= $i ?>&search=<?= $this->view->search ?>"><?= $i ?></a>
							</li>

						<?php }; ?>

						<li class="page-item">
							<a class="page-link" href="?page=<?= $this->view->total_paginas ?>&search=<?= $this->view->search ?>">Última</a>
						</li>
					</ul>
				</nav>
			</div>

		</div>
	</div>
</div>